1hr/workspace/myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    # path("post/<int:post_id>/", views.detail, name="detail")   --> this wont take the string values
    path("post/<str:slug>/", views.detail, name="detail"),
    path("new_url/", views.new_url_view, name="new_page_url"),
    path("old_url/", views.old_url_redirect, name="old_url"),
    path("contact/", views.contact_view, name="contact")

]

1hr/workspace/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path('blog/', include("blog.urls")),
    path('admin/', admin.site.urls),

]

1hr/workspace/myapp/blog/models.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True) # default max_length=200, blank=True means its a nullabe column
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'

1hr/workspace/myapp/blog/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)
    email = forms.EmailField(label='Email', required=True)
    message = forms.CharField(label='Message', required=True)

1hr/workspace/myapp/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
import logging
from .models import Post
from django.core.paginator import Paginator
from .forms import ContactForm

# Create your views here.

# posts = [
#     {'id': 1, 'title': 'Post 1', 'content': 'Content for Post 1'},
#     {'id': 2, 'title': 'Post 2', 'content': 'Content for Post 2'},
#     {'id': 3, 'title': 'Post 3', 'content': 'Content for Post 3'},
#     {'id': 4, 'title': 'Post 4', 'content': 'Content for Post 4'},
# ]

def index(request):
    # return HttpResponse("Hello World, You are at blog's index")
    blog_title = "Latest Post"
    all_posts = Post.objects.all()

    #paginate
    paginator = Paginator(all_posts, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/index.html', {'blog_title': blog_title, 'page_obj': page_obj})
    
def detail(request, slug):
    # return HttpResponse(f"You are viewing post details page {post_id}")
    # static data
    # post = next((item for item in posts if item['id'] == int(post_id)), None)

    # getting data from model by post id
    try:
        post = Post.objects.get(slug=slug)
        related_posts = Post.objects.filter(category=post.category).exclude(pk=post.id)
    except Post.DoesNotExist:
        raise Http404("Post Does not Exists!ss")

    logger = logging.getLogger("TESTING")
    logger.debug(f'post variable is {post}')
    return render(request, 'blog/detail.html', {'post': post, 'related_posts':related_posts})

def old_url_redirect(request):
    # return redirect("new_url") 
    # instead of hard coding this url we can use reverse from djano.urls
    return redirect(reverse('blog:new_page_url'))


def new_url_view(request):
    return HttpResponse("This is the new URL")

def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')


        logger = logging.getLogger("TESTING")
        if form.is_valid():
            logger.debug(f'POST data is {form.cleaned_data['name'], form.cleaned_data['email'], form.cleaned_data['message']}')
            success_message = 'Your form is accepted'
            # send email or save in database
            return render(request, 'blog/contact.html', {'form':form, 'success_message':success_message})
        else:
            logger.debug('Form validation failure')
        return render(request, 'blog/contact.html', {'form':form, 'name':name, 'email':email, 'message':message})
    return render(request, 'blog/contact.html')

1hr/workspace/myapp/myapp/views.py
from django.shortcuts import render

def custom_page_not_found(request, exception):
    return render(request, '404.html', status=404)

1hr/workspace/myapp/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- we are passing the blog_title only in index function but not in detail function so it will be empty
    so we are setting a default value if it is not passed her -->
    <title>{{blog_title | default:"Document"}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    
    <!-- Header -->
    {% include 'blog/includes/header.html' %}

    <!-- dynamic content -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    {% include 'blog/includes/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

1hr/workspace/myapp/blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <!-- Error Messages -->
                {% for field in form %}
                    {% if field.errors %}
                        <div class="col-12">
                            <span class="fw-bold">{{field.label_tag}}</span>
                            {% for error in field.errors %}
                                <span class="fw-bold">{{error}}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}
                
                <!-- Success Message -->
                
                {% if success_message %}
                    <div class="alert alert-success" role="alert">
                        {{success_message}}
                    </div>
                {% endif %}

                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{name}}">
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{email}}">
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" value="{{message}}"></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
{% endblock %}

1hr/workspace/myapp/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style="font-size:18px">({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at | date:"F j, Y"}}</p> <!--F(month), j(date without zero), Y(year)-->
              <img src={{post.img_url}} class="img-fluid mb-4" alt="Blog Image">
              {% comment %} <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur tortor vel magna tincidunt tempus. Maecenas eget maximus eros. Vivamus id nisl lacus. Donec et risus turpis. In nec efficitur purus, ac faucibus nulla. Aenean nec malesuada velit. Quisque ac mauris ac turpis semper interdum.</p>
              <p>Sed et lorem et lacus consequat suscipit. Vestibulum dapibus sapien et eros aliquam, a dictum leo vehicula. Aliquam consequat turpis vitae lectus tristique, quis efficitur orci fermentum. Phasellus a ligula pulvinar, blandit eros at, euismod nisl. Nam pharetra urna id purus volutpat, a feugiat magna convallis. Curabitur vestibulum velit sit amet nisl sollicitudin, eget rutrum enim fermentum.</p>
              <p>Donec quis nisi vitae metus sodales fermentum ac eu eros. Nulla facilisi. Fusce bibendum nisl et varius vehicula. Duis volutpat convallis justo nec pharetra. Cras convallis dolor vitae hendrerit mollis. Curabitur ultrices odio vitae sapien fringilla rhoncus. Ut feugiat condimentum ligula, vel faucibus neque sollicitudin sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam eget mauris hendrerit, lobortis urna id, sollicitudin est. Nam semper aliquam magna, non egestas orci elementum ac.</p> {% endcomment %}
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% comment %} <li><a href="./detail.html">Post 1</a></li>
                    <li><a href="./detail.html">Post 2</a></li>
                    <li><a href="./detail.html">Post 3</a></li> {% endcomment %}
                    {% for related_post in related_posts %}
                      <li><a href={% url "blog:detail" slug=related_post.slug %}>{{related_post.title}}</a></li>
                    {% endfor %}

                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

1hr/workspace/myapp/blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3 fixed-bottom">
    <div class="col-4 d-flex justify-content-center align-items-center">
        <span class="text-light">© 2021 Company, Inc</span>
    </div>
</footer>

1hr/workspace/myapp/blog/templates/blog/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="row">
        <div class="col">
            <a class="text-light text-decoration-none" href="/blog" ><h3>Blog</h3></a>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="">Home</a>
                <a class="text-light text-decoration-none" href="">About</a>
                <a class="text-light text-decoration-none" href="">Contact</a>
            </div>
        </div>
    </div>
</header>

1hr/workspace/myapp/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <!-- upper: it is a filter -->
                <h2 >{{ blog_title | upper }}</h2>

                <!-- length filter it show only the lenght of the string -->
                <!-- <h2 >{{ blog_title | length }}</h2> -->

                <!-- used to show only limited words -->
                <!-- <h2 >{{ blog_title | truncatewords:1 }}</h2> -->
                <!-- output: Latest... it will hide the words after first word and replace those all with ... -->
                <!-- ... this is called text elipsis -->


            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                        <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                    </div>
            </div>
        </div>
        <div class="row m-3">
            {% if page_obj %}
                {% for post in page_obj %}
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img style="height: 300 , width: 300" src="{{post.img_url}}" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    {% comment %} <h5 class="card-title">Post title</h5>
                                    <p class="card-text">Some quick example text for the post's content.</p> {% endcomment %}
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">{{post.content | truncatechars:70}}</p>
                                    <div class="d-flex justify-content-between">
                                            {% comment %} <a href="./detail.html">Read More</a> {% endcomment %}
                                            {% comment %} this is hard coded {% endcomment %}
                                            {% comment %} <a href="/blog/post/{{post.id}}">Read More</a> {% endcomment %}

                                            {% comment %} dynamic way {% endcomment %}
                                            <a href= {% url "blog:detail" slug=post.slug %}>Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% comment %} <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">Post title</h5>
                                    <p class="card-text">Some quick example text for the post's content.</p>
                                    <div class="d-flex justify-content-between">
                                            <a href="./detail.html">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Development</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">Post title</h5>
                                    <p class="card-text">Some quick example text for the post's content.</p>
                                    <div class="d-flex justify-content-between">
                                            <a href="./detail.html">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Engineering</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">Post title</h5>
                                    <p class="card-text">Some quick example text for the post's content.</p>
                                    <div class="d-flex justify-content-between">
                                            <a href="./detail.html">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Kids</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">Post title</h5>
                                    <p class="card-text">Some quick example text for the post's content.</p>
                                    <div class="d-flex justify-content-between">
                                            <a href="./detail.html">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Design</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">Post title</h5>
                                    <p class="card-text">Some quick example text for the post's content.</p>
                                    <div class="d-flex justify-content-between">
                                            <a href="./detail.html">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Movies</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 my-3">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                            <li class="page-item"><span class="page-link">Page 3 of 20.</span></li>
                            <li class="page-item">
                                <a class="page-link" href="?page=4" aria-label="Next">
                                    <span aria-hidden="true">next</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page=20" aria-label="Last">
                                    <span aria-hidden="true">last &raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    
                </div>
            </div> {% endcomment %}
            {% endfor %}
                <div class="col-12 my-3">
                    {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                            {% endif %}
                            <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span></li>
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">next</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                    <span aria-hidden="true">last &raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            {% else %}
                <p> No Posts Available</p>
        {% endif %}
        <div class="row">
        
        </div>
        
    </div>
{% endblock %}